name: unit-test
inputs:
  codecov_token:
    required: true
runs:
  using: composite
  steps:
    - name: run unit test
      shell: bash
      run: |
        nix build --print-build-logs .#unit-test-epoll
        cp result/coverage_epoll.txt coverage_epoll.txt
        nix build --print-build-logs .#unit-test-uring
        cp result/coverage_io_uring.txt coverage_io_uring.txt
    - name: upload epoll coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov_token }}
        flags: epoll
        files: coverage_epoll.txt
        fail_ci_if_error: true
        verbose: true
    - name: upload uring coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov_token }}
        flags: uring
        files: coverage_io_uring.txt
        fail_ci_if_error: true
        verbose: true
    - name: upload tests coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov_token }}
        flags: tests
        files: coverage_epoll.txt,coverage_io_uring.txt
        fail_ci_if_error: true
        verbose: true
