name: unit-test
inputs:
  codecov_token:
    required: true
runs:
  using: composite
  steps:
    - name: run unit test
      shell: bash
      run: nix build --print-build-logs .#unittest
    - name: upload epoll coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov_token }}
        flags: epoll
        files: result/coverage_epoll.txt
        fail_ci_if_error: true
        verbose: true
    - name: upload uring coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov_token }}
        flags: uring
        files: result/coverage_uring.txt
        fail_ci_if_error: true
        verbose: true
    - name: upload tests coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov_token }}
        flags: tests
        files: result/coverage_epoll.txt,result/coverage_uring.txt
        fail_ci_if_error: true
        verbose: true
