#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

find . -type f \( -name \*.cc -or -name \*.h -or -name \*.ccm \) -not -path ./build/\* | xargs clang-format --Werror --fcolor-diagnostics -i --verbose
