coverage:
  status:
    project:
      default: false
      tests:
        target: 98%
        if_not_found: failure
        if_ci_failed: error
        paths:
          - tests/
      lib:
        target: 90%
        if_not_found: failure
        if_ci_failed: error
        paths:
          - src/