flag_management:
  default_rules:
    statuses:
      - type: project
        target: 90%
      - type: patch
        target: 90%
  individual_flags:
    - name: epoll
      paths:
        - "include/"
        - "!include/xyco/fs/io_uring/"
        - "!include/xyoc/io/io_uring/"
        - "!include/xyco/net/io_uring/"
        - "src/"
        - "!src/fs/io_uring/"
        - "!src/io/io_uring/"
        - "!src/net/io_uring/"
    - name: uring
      paths:
        - "include/"
        - "!include/xyco/fs/epoll/"
        - "!include/xyoc/io/epoll/"
        - "!include/xyco/net/epoll/"
        - "src/"
        - "!src/fs/epoll/"
        - "!src/io/epoll/"
        - "!src/net/epoll/"
    - name: tests
      paths:
        - "tests/"
      statuses:
        - type: project
          target: 98%
