flag_management:
  default_rules:
    statuses:
      - type: project
        target: 90%
      - type: patch
        target: 90%
  individual_flags:
    - name: epoll
      paths:
        - !src/fs/io_uring/
        - !src/io/io_uring/
        - !src/net/io_uring/
    - name: uring
      paths:
        - !src/fs/io_epoll/
        - !src/io/io_epoll/
        - !src/net/io_epoll/
