name: xyco ci

on:
  pull_request:
    branches:
      - "main"
      - "build/*"

env:
  llvm_version: 17

jobs:
  rust-tool:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            tools/target/
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          rustup override set nightly && rustup component add clippy
          cargo clippy --manifest-path tools/Cargo.toml --all-targets -- -D warnings
          cargo test --manifest-path ./tools/Cargo.toml

  cpp-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install essential packages
        run: |
          sudo apt-get install -y ninja-build liburing-dev libboost-all-dev
          sudo bash scripts/install_llvm.sh $llvm_version
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            tools/target/
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - name: build
        run: |
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_CXX_COMPILER=clang-$llvm_version -S . -B build -G "Ninja"
          cmake --build build --config Release --target all
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_CXX_COMPILER=clang-$llvm_version -DXYCO_ENABLE_LOGGING=ON -S . -B build -G "Ninja"
          cmake --build build --config Release --target all
          rustup override set nightly
          cargo run --manifest-path tools/Cargo.toml -p git-hooks -- check clang-format --source src benchmark tests examples --tool-version $llvm_version
          cargo run --manifest-path tools/Cargo.toml -p git-hooks -- check clang-tidy --source include src benchmark examples --build build --tool-version $llvm_version --extra-arg="-I/usr/lib/llvm-$llvm_version/include/c++/v1/"

  cpp-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install essential packages
        run: |
          sudo apt-get install -y ninja-build lcov liburing-dev libboost-all-dev
          sudo bash scripts/install_llvm.sh $llvm_version
      - name: test
        run: |
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_CXX_COMPILER=clang-$llvm_version -DXYCO_ENABLE_LOGGING=ON -S . -B build -G "Ninja"
          cmake --build build --config Release --target xyco_test_epoll xyco_test_uring
          LLVM_PROFILE_FILE="build/tests/xyco_test_epoll.profraw" build/tests/xyco_test_epoll --gtest_repeat=100 --gtest_break_on_failure --gtest_shuffle --gtest_death_test_style=threadsafe
          llvm-profdata-$llvm_version merge -sparse build/tests/xyco_test_epoll.profraw -o build/tests/xyco_test_epoll.profdata
          llvm-cov-$llvm_version show build/tests/xyco_test_epoll -ignore-filename-regex=build -instr-profile=build/tests/xyco_test_epoll.profdata > coverage_epoll.txt
          LLVM_PROFILE_FILE="build/tests/xyco_test_uring.profraw" build/tests/xyco_test_uring --gtest_repeat=100 --gtest_break_on_failure --gtest_shuffle --gtest_death_test_style=threadsafe
          llvm-profdata-$llvm_version merge -sparse build/tests/xyco_test_uring.profraw -o build/tests/xyco_test_uring.profdata
          llvm-cov-$llvm_version show build/tests/xyco_test_uring -ignore-filename-regex=build -instr-profile=build/tests/xyco_test_uring.profdata > coverage_uring.txt
      - name: upload epoll coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: epoll
          files: coverage_epoll.txt
          fail_ci_if_error: true
          verbose: true
      - name: upload uring coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: uring
          files: coverage_uring.txt
          fail_ci_if_error: true
          verbose: true
      - name: upload tests coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: tests
          files: coverage_epoll.txt,coverage_uring.txt
          fail_ci_if_error: true
          verbose: true
