name: codecov

on:
  push:
    branches:
      - "main"
      - "build/*"

env:
  llvm_version: 14

jobs:
  test-codecov:
    runs-on: ubuntu-22.04
    steps:
      - name: install essential packages
        run: |
          sudo apt-get install -y ninja-build lcov default-jdk libunwind-$llvm_version-dev liburing-dev
      - uses: actions/checkout@v3
      - name: test
        run: |
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_CXX_COMPILER=clang++-$llvm_version -S . -B ./build -G "Ninja"
          cmake --build ./build --config Release --target xyco_test_epoll xyco_test_uring
          bazel coverage --config=opt --config=coverage --test_output=all //tests:xyco_test_epoll --test_arg=--gtest_repeat=100 --test_arg=--gtest_break_on_failure --test_arg=--gtest_shuffle
          bazel coverage --config=opt --config=coverage --test_output=all //tests:xyco_test_uring --test_arg=--gtest_repeat=100 --test_arg=--gtest_break_on_failure --test_arg=--gtest_shuffle
      - name: upload epoll coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: epoll
          files: $(bazel info bazel-testlogs)/tests/xyco_test_epoll/coverage.dat
          fail_ci_if_error: true
          verbose: true
      - name: upload uring coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: uring
          files: $(bazel info bazel-testlogs)/tests/xyco_test_uring/coverage.dat
          fail_ci_if_error: true
          verbose: true
      - name: upload tests coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: tests
          files: $(bazel info bazel-testlogs)/tests/xyco_test_epoll/coverage.dat,$(bazel info bazel-testlogs)/tests/xyco_test_uring/coverage.dat
          fail_ci_if_error: true
          verbose: true

  push-dev-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ddxy18/xyco-dev:latest
