name: codecov

on:
  push:
    branches:
      - "main"
      - "build/*"

env:
  llvm_version: 14

jobs:
  test-codecov:
    runs-on: ubuntu-22.04
    steps:
      - name: install essential packages
        run: |
          sudo apt-get install -y lcov libunwind-$llvm_version-dev liburing-dev libboost-all-dev
      - uses: actions/checkout@v3
      - name: test
        run: |
          bazel coverage --config=opt --config=coverage --config=enable_logging --test_output=all //tests:xyco_test_epoll --test_arg=--gtest_repeat=100 --test_arg=--gtest_break_on_failure --test_arg=--gtest_shuffle --test_arg=--gtest_death_test_style=threadsafe
          bazel coverage --config=opt --config=coverage --config=enable_logging --test_output=all //tests:xyco_test_uring --test_arg=--gtest_repeat=100 --test_arg=--gtest_break_on_failure --test_arg=--gtest_shuffle --test_arg=--gtest_death_test_style=threadsafe
          mv $(bazel info bazel-testlogs)/tests/xyco_test_epoll/coverage.dat coverage_epoll.dat && mv $(bazel info bazel-testlogs)/tests/xyco_test_uring/coverage.dat coverage_uring.dat
      - name: upload epoll coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: epoll
          files: coverage_epoll.dat
          fail_ci_if_error: true
          verbose: true
      - name: upload uring coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: uring
          files: coverage_uring.dat
          fail_ci_if_error: true
          verbose: true
      - name: upload tests coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: tests
          files: coverage_epoll.dat,coverage_uring.dat
          fail_ci_if_error: true
          verbose: true

  push-dev-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ddxy18/xyco-dev:latest
