name: codecov

on:
  push:
    branches:
      - "main"
      - "build/*"

env:
  llvm_version: 14

jobs:
  test-codecov:
    runs-on: ubuntu-22.04
    steps:
      - name: install essential packages
        run: |
          sudo apt install -y ninja-build libunwind-$llvm_version-dev liburing-dev
      - uses: actions/checkout@v3
      - name: test
        run: |
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_CXX_COMPILER=clang++-$llvm_version -S . -B ./build -G "Ninja"
          cmake --build ./build --config Release --target xyco_test_epoll xyco_test_uring
          sudo LLVM_PROFILE_FILE="./build/tests/xyco_test_epoll.profraw" ./build/tests/xyco_test_epoll --gtest_repeat=100 --gtest_break_on_failure --gtest_shuffle --gtest_brief=1
          llvm-profdata-$llvm_version merge -sparse ./build/tests/xyco_test_epoll.profraw -o ./build/tests/xyco_test_epoll.profdata
          llvm-cov-$llvm_version show ./build/tests/xyco_test_epoll -ignore-filename-regex=./build -instr-profile=./build/tests/xyco_test_epoll.profdata > ./build/tests/coverage_eopll.txt
          sudo LLVM_PROFILE_FILE="./build/tests/xyco_test_uring.profraw" ./build/tests/xyco_test_uring --gtest_repeat=100 --gtest_break_on_failure --gtest_shuffle --gtest_brief=1
          llvm-profdata-$llvm_version merge -sparse ./build/tests/xyco_test_uring.profraw -o ./build/tests/xyco_test_uring.profdata
          llvm-cov-$llvm_version show ./build/tests/xyco_test_uring -ignore-filename-regex=./build -instr-profile=./build/tests/xyco_test_uring.profdata > ./build/tests/coverage_uring.txt
      - name: upload epoll coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: epoll
          files: ./build/tests/coverage_eopll.txt
          fail_ci_if_error: true
          verbose: true
      - name: upload uring coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: uring
          files: ./build/tests/coverage_uring.txt
          fail_ci_if_error: true
          verbose: true
      - name: upload tests coverage report
        uses: codecov/codecov-action@v3
        with:
          flags: tests
          files: ./build/tests/coverage_eopll.txt,./build/tests/coverage_uring.txt
          fail_ci_if_error: true
          verbose: true

  push-dev-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ddxy18/xyco-dev:latest
